services:
  - type: web
    name: fact-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    build:
      commands:
        - apt-get update && apt-get install -y wget gnupg2
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - apt install -y ./google-chrome-stable_current_amd64.deb || true
